kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang:1.19
    commands:
      - go test -coverprofile=cover.out ./...
      - go tool cover -func=cover.out

  - name: build
    image: golang:1.19
    commands:
      - GOOS=linux   GOARCH=amd64   go build -ldflags "-X github.com/harness/harness-migrate/cmd.version=${DRONE_TAG##v}" -o release/harness-migrate-linux-amd64
      - GOOS=linux   GOARCH=arm64   go build -ldflags "-X github.com/harness/harness-migrate/cmd.version=${DRONE_TAG##v}" -o release/harness-migrate-linux-arm64
      - GOOS=darwin  GOARCH=amd64   go build -ldflags "-X github.com/harness/harness-migrate/cmd.version=${DRONE_TAG##v}" -o release/harness-migrate-darwin-amd64
      - GOOS=darwin  GOARCH=arm64   go build -ldflags "-X github.com/harness/harness-migrate/cmd.version=${DRONE_TAG##v}" -o release/harness-migrate-darwin-arm64
      - GOOS=windows GOARCH=amd64   go build -ldflags "-X github.com/harness/harness-migrate/cmd.version=${DRONE_TAG##v}" -o release/harness-migrate-windows-amd64.exe

      - tar -cvzf release/harness-migrate-linux-amd64.tar.gz   -C release harness-migrate-linux-amd64
      - tar -cvzf release/harness-migrate-linux-arm64.tar.gz   -C release harness-migrate-linux-arm64
      - tar -cvzf release/harness-migrate-darwin-amd64.tar.gz  -C release harness-migrate-darwin-amd64
      - tar -cvzf release/harness-migrate-darwin-arm64.tar.gz  -C release harness-migrate-darwin-arm64
      - tar -cvzf release/harness-migrate-windows-amd64.tar.gz -C release harness-migrate-windows-amd64.exe

      - sha256sum release/*.tar.gz > release/harness-migrate-checksums.txt
  - name: publish docker-amd64
    image: plugins/docker
    pull: if-not-exists
    settings:
      repo: harness/harness-migrate
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/Dockerfile.linux.amd64
      username:
        from_secret: harness-docker-username
      password:
        from_secret: harness-docker-password
    when:
      ref:
        - refs/heads/master
        - refs/tags/v*

  - name: publish docker-arm64
    image: plugins/docker
    pull: if-not-exists
    settings:
      repo: harness/harness-migrate
      auto_tag: true
      auto_tag_suffix: linux-arm64
      dockerfile: docker/Dockerfile.linux.arm64
      username:
        from_secret: harness-docker-username
      password:
        from_secret: harness-docker-password
    when:
      ref:
        - refs/heads/master
        - refs/tags/v*

  - name: release
    image: plugins/github-release
    settings:
      files:
        - release/harness-migrate-*.tar.gz
        - release/harness-migrate-checksums.txt
      api_key:
        from_secret: github_token
    when:
      ref:
        - refs/tags/v*

trigger:
  branch:
    - master
    - refs/tags/v*

---
kind: pipeline
type: docker
name: docker manifest

steps:
  - name: manifest
    image: plugins/manifest
    settings:
      spec: docker/manifest.tmpl
      auto_tag: true
      ignore_missing: true
      password:
        from_secret: harness-docker-password
      username:
        from_secret: harness-docker-username

depends_on:
  - default
trigger:
  ref:
    - refs/heads/master
    - refs/tags/v*
